### ISSUE TITLE
fix infinite loop

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lucene-sa#11]
I've added a test producing an infinite loop in https://github.com/BuddhistDigitalResourceCenter/lucene-sa/commit/cbe19433a19ddfc1e00a067b9b9567a27ed8b825 (it seems to happen only with IAST, maybe it's in the filters). Also, please test the following list and make sure there's no infinite loop:

[iast.zip](https://github.com/BuddhistDigitalResourceCenter/lucene-sa/files/2147403/iast.zip)

**Comment by drupchen** [comment]
solved with [`2e7d173`](https://github.com/BuddhistDigitalResourceCenter/lucene-sa/commit/2e7d173a24bf68525762561050a908b14fedd463)
