### ISSUE TITLE
sa-x-ndia too lenient? sa-x-iast too strict?

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/lucene-sa#15]
The following query:

    select ?s ?lbl
    where {
      (?s ?sc ?lbl) text:query "manjushri"@sa-x-ndia
    } limit 100

returns results like:

    1	bdr:T2GS1087    "mahamaya"@sa-alalc97
    2	bdr:W0RTA1407   "āryamañjuśrīnāmasaṃgīti-nāma-homakrama"@sa-x-iast
    3	bdr:W0RTT1407   "āryamañjuśrīnāmasaṃgīti-nāma-homakrama"@sa-x-iast
    4	bdr:T233        "madhyamaka"@sa-alalc97
    5	bdr:T732        "mamaki devi"@sa-alalc97

which includes results fairly far away from ``manjushri``.

On the other hand the query:

    select ?s ?lbl
    where {
      (?s ?sc ?lbl) text:query "mañjuśrī"@sa-x-iast
    } limit 100

returns no results?!

**Comment by xristy** [comment]
with the latest ``lucene-sa-1.0.2.jar`` and the current ttl.erb/bdrc.ttl the first query above now returns only results with ``manjushri`` which is an improvement but now there are **no** ``sa-x-iast`` results such as ``bdr:W0RTA1407`` and ``bdr:W0RTT1407``.

I have not re-indexed so maybe that's an issue.

The second query now finds a total of 100 results

**Comment by xristy** [comment]
More info.

The query:

    select ?s ?lbl
    where {
      (?s ?sc ?lbl) text:query (rdfs:label "manjushri"@sa-x-ndia)
    } limit 1000

returns 60 results - all of which are ``sa-x-ndia``.

OTOH, the query:

    select ?s ?lbl
    where {
      (?s ?sc ?lbl) text:query (rdfs:label "manju"@sa-x-ndia)
    } limit 1000

returns a total of 925 results which are a mix of ``sa-x-ndia``, ``sa-alalc97``, and ``sa-x-iast``. Many of the ``sa-x-iast`` results include ``mañjuśrī`` as well as other results that include the substring ``mañju``.

So one question is why the second query returns non-ndia ``manjushri`` results but the first query doesn't

Could this be some sort of max-match interaction?

**Comment by eroux** [comment]
I think this could be closed @xristy ?
