### ISSUE TITLE
fuzzy / lenient  search 

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lucene-sa#4]
As asked by [84000](http://84000.co/) and other partners, it should be possible to index text so that it can be searched in a more forgiving way.

There could be several levels of leniency. Here is one proposed by a partner (using IAST transliteration):
- searching `a` or `ā` should return results with `a` and `ā` (also applies to other vowels)
- searching `h` or `ḥ` should return results with `h`, `ḥ`, `x` or `f`
- searching `ṇ`, `ṅ`, `ñ`, `n`, `m` or `ṃ` should return results with either of these
- searching for a single consonant among `k`, `g`, `ṭ`, `ḍ`, `t`, `d`, `n`, `p`, `b`, `m` should return results with either single or double consonants
- searching for a double consonant in the list of previous item should only return results with double consonants, not single ones. This will probably be quite difficult to implement in Lucene so it may be just an option. The easiest way is to return either single or double consonants in this case

A step further in leniency (for broad audience projects like 84000) would be:
- searching `sh`, `s`, `ś` or `ṣ` would return results with either `s`, `ś` or `ṣ`
- searching `X` or `Xh` would return terms with either, where `X` is: `k`, `g`, `c`, `t`, `d`, `b`, `j`, `p`, `ṭ`, `ḍ`

**Comment by eroux** [comment]
Some hints for implementation in case someone wants to take care of it: the idea is to simplify the tokens returned by the tokenizer before they are stored in the index. 

So an example of the data flow could be the following:

- during indexing:
  - original text (in IAST) contains `ā`
  - gets transformed into SLP1 as `A`
  - the tokenizer returns a token containing the SLP1 `A`
  - a new `LenientSearchFilter` would transform it into SLP1 `a`
  - the index contains character `a`
- during a search where user asks for IAST character `a` or `ā`:
  - Lucene translates the query into SLP1 using character `a` or `A`
  - Lucene uses the tokenizer on the search string, returning a token containing `a` or `A`
  - Lucene calls `LenientSearchFilter` that transforms the token so that it contains character `a` in both cases
  - Lucene finds match of this new token into the index and finds tokens which original characters in IAST were `a` or `ā` with no difference

**Comment by drupchen** [comment]
The first thought that comes is that modifying the index in that way makes it impossible to get back the exact search in case it is needed (except if we build two indexes, of course).

I would rather see us acheive the same results by performing query expansion of all queries that contain `ā` into a query containing the `OR` operator. Ex. `sātmi` would first be expanded into `satmi OR sAtmi` and then only passed on to the index.

How about that ?

**Comment by eroux** [comment]
Well, that means that for 10 characters you would have at least 1024 possibilities (probably more), for instance your example could also be (in IATS) `ṣāṭhṃī` and all sorts of combinatin (a first approximation would actually be around 400 possibilities for your small example), doesn't look scalable...

**Comment by eroux** [comment]
(so yes, two indexes is what I'm thinking about if you want to have two types of search)

**Comment by drupchen** [comment]
as getting different results in the query and the indexing processes, it is very easily acheived by creating a modified LenientSearchFilter and use it instead of this one to parse the query.
